###
get http://localhost:1337/getUserResult?handle=dskjbaksj&contestID=START66B



####
post http://localhost:1337/login/verify
Content-Type: application/json

{
    "username":"vivek",
    "token":"963847"
}
###
get http://localhost:1337/getEvents?eventID=3&username=abcdef


###
get http://localhost:1337/getHandlesInfo?username=a

###
get http://localhost:1337/event/getCandidates?eventID=1

###
get http://localhost:1337/event/getCandidateInfo?eventID=1&username=a

### 
get http://localhost:1337/checkUserCodeChef?handle=sanath12345&fullName=RaXmebkDPdpjbft




###
post http://localhost:1337/login/getotp
Content-Type: application/json

{
    "username":"vivek"
}

###
get http://localhost:1337/event/getQuestions?eventID=1

###
get http://localhost:1337/room/getHandleFromRoom?username=sktime&eventID=1&roomID=bf785b35-ea48-4143-b09b-ad4426d15e80

###
post http://localhost:1337/createEvent
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNrdGltZSIsImVtYWlsIjoiYWJjQGEuY29tIiwiY29sb3IiOiIjMzY4NTUxIiwiaWF0IjoxNjcyMDg0NjAxLCJleHAiOjE2NzI5ODQ2MDEsImlzcyI6IlAyUCJ9.a9yxAY6QnOJWGp4lyKqX-9jjHl4HPNofmCRdsqbjSc0

{
    "name": "round 325",
    "date": 1672088143037,
    "section": "codeforces",
    "dependent":{"questions":[{"code":"A","name":"alice"},{"code":"B","name":"bob"},{"code":"C","name":"alice1"},{"code":"D","name":"alice2"},{"code":"E","name":"alice3"}]},
    "candidatesInfo":[
        {
            "username":"sktime",
            "handle":"sanath_kumar",
            "rating":1489,
            "solved":["A","B","C"]
        },
        {
            "username":"sktime1",
            "handle":"sanath_kumar1",
            "rating":1500,
            "solved":["A","B"]
        },
        {
            "username":"sktime2",
            "handle":"sanath_kumar2",
            "rating":1200,
            "solved":["A","B"]
        },
        {
            "username":"sktime3",
            "handle":"sanath_kumar3",
            "rating":1900,
            "solved":["B","C"]
        },
        {
            "username":"sktime4",
            "handle":"sanath_kumar4",
            "rating":2000,
            "solved":["A","C"]
        },
        {
            "username":"sktime5",
            "handle":"sanath_kumar5",
            "rating":1600,
            "solved":["A","B","C"]
        },
        {
            "username":"sktime6",
            "handle":"sanath_kumar6",
            "rating":1700,
            "solved":[]
        },
        {
            "username":"sktime7",
            "handle":"sanath_kumar7",
            "rating":800,
            "solved":["A"]
        },
        {
            "username":"sktime8",
            "handle":"sanath_kumar8",
            "rating":1100,
            "solved":["A"]
        },
        {
            "username":"sktime9",
            "handle":"sanath_kumar9",
            "rating":1150,
            "solved":["A"]
        },
        {
            "username":"sktime10",
            "handle":"sanath_kumar10",
            "rating":2500,
            "solved":["A","B","C","D"]
        },
        {
            "username":"sktime11",
            "handle":"sanath_kumar11",
            "rating":1600,
            "solved":["A","B","C"]
        },
        {
            "username":"sktime12",
            "handle":"sanath_kumar12",
            "rating":700,
            "solved":[]
        },
        {
            "username":"sktime13",
            "handle":"sanath_kumar13",
            "rating":2007,
            "solved":["A","C"]
        },
        {
            "username":"sktime14",
            "handle":"sanath_kumar14",
            "rating":1400,
            "solved":["B","C"]
        },
        {
            "username":"sktime15",
            "handle":"sanath_kumar15",
            "rating":1984,
            "solved":[]
        },
        {
            "username":"sktime16",
            "handle":"sanath_kumar16",
            "rating":1900,
            "solved":["A","B","C"]
        },
        {
            "username":"sktime5",
            "handle":"sanath_kumar5",
            "rating":1400,
            "solved":["A","B"]
        },
        {
            "username":"sktime17",
            "handle":"sanath_kumar17",
            "rating":1760,
            "solved":["A","C"]
        },
        {
            "username":"sktime18",
            "handle":"sanath_kumar18",
            "rating":1670,
            "solved":["A","B","C"]
        },
        {
            "username":"sktime19",
            "handle":"sanath_kumar19",
            "rating":1876,
            "solved":["A","B","C","D"]
        }
    ]
}


###
post http://localhost:1337/event/register
Content-Type: application/json

{
    "username": "sktime1",
    "eventID": 1,
    "section":"codechef"
}



###
post http://localhost:1337/login
Content-Type: application/json

{
    "username":"sanath_kumar",
    "password":"abcdef"
}

###
get http://localhost:1337/logout
        
###
post http://localhost:1337/feed
Content-Type: application/json

{
    "content":"England's umpteenth batting collapse in Hobart and their meek concession of the series also kind of left their victors a little unsure of their own supremacy"
}

###
get http://localhost:1337/feed

###
get http://localhost:1337/feed/1


###
post http://localhost:1337/like

###
get http://localhost:1337/network

###
post http://localhost:1337/network/pending-connection
Content-Type: application/json

{
    "celebrity":1
}

###
post http://localhost:1337/network/new-connection
Content-Type: application/json

{
    "fan":11
}

###
get http://localhost:1337/network/my-connections

###
post http://localhost:1337/network/decline-connection
Content-Type: application/json

{
    "enemy":9
}

###
get http://localhost:1337/profile/profile-details

### 
post http://localhost:1337/profile/view-profile
Content-Type: application/json

{
    "view_user":"harsha"
}

###
post http://localhost:1337/profile/del-request
Content-Type: application/json

{
    "celebrity":2
}

###
post http://localhost:1337/profile/del-connection
Content-Type: application/json

{
   "other":11
}

###
post http://localhost:1337/post/likes
Content-Type: application/json

{
    "post_id":1
}

###
post http://localhost:1337/post/dislikes
Content-Type: application/json

{
    "post_id":1
}

###
get http://localhost:1337/post/likes/1

### Get all Questions
get http://localhost:1337/question/all?examId=639b802c00e2f12db658a030
Content-Type: application/json


### Post a question
post http://localhost:1337/question/question
Content-Type: application/json

{
        "examId":"639b802c00e2f12db658a030",
        "subjectType":"Maths",
        "questionDescription":"1+2",
        "answer":[false, true, false, false],
        "options":["0", "3", "4", "5"]
} 

### exam info
post http://localhost:1337/exam/examInfo
Content-Type: application/json

{
    "examName":"Weekend",
    "examType":"JEE",
    "examDate":"Thu Apr 03 2014"
}

#### ubidots
post https://industrial.api.ubidots.com/api/v1.6/variables/639b7582e08182000e509e82/values
Content-Type: application/json
X-Auth-Token: BBFF-ZL79ZGgIK6SUE8qMOlprUzd621EYG6

{
    "value": 10,
    "timestamp": 1634311791000,
    "context": {
      "status": "cold"
    }
}